# Generated by Django 3.1.2 on 2022-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_volunteer_is_helping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='helper',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
